### ISSUE TITLE
pourquoi final ? et pourquoi pas Autowired une fois ?

### ISSUE THREAD

**Issue by StephaneBlackPanther** [DENMOUNS/premier_projet#39]
https://github.com/DENMOUNS/premier_projet/blob/b872debeecbaf052e18e0dd2513d961e405d3743/garage/src/main/java/com/garageapp/garage/controller/UserController.java#LL16C5-L21C6

**Comment by DENMOUNS** [comment]
final parce que je veux être sûre de la nature des données qui arrivent, et
j'injecte les dépendances ainsi parceque dans l'encapsulation c'est la
meilleure méthode par rapport a @Autowired
    private final UserService userService;
