### ISSUE TITLE
a quoi ca sert?

### ISSUE THREAD

**Issue by StephaneBlackPanther** [DENMOUNS/premier_projet#41]
https://github.com/DENMOUNS/premier_projet/blob/b872debeecbaf052e18e0dd2513d961e405d3743/garage/src/main/java/com/garageapp/garage/restservicecors/RestServiceCorsApplication.java#L3

**Comment by DENMOUNS** [comment]
je voulais gérer l'erreur cors et vraiment j'ai oublie de supprimer cela,
donc je vais supprimer ca maintenant

**Comment by DENMOUNS** [comment]
je voulais gérer l'erreur cors et vraiment j'ai oublie de supprimer cela,
donc je vais supprimer ca maintenant
